<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Du lịch Hóc Môn</title>
  <!-- Bootstrap CSS từ CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      padding-top: 56px;
    }
    .hero {
      background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Cho_Hoc_Mon.JPG/1280px-Cho_Hoc_Mon.JPG');
      background-size: cover;
      background-position: center;
      color: white;
      height: 400px;
      text-align: center;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .hero h1 {
      font-size: 4rem;
    }
  </style>
</head>
<body>
  <!-- Thanh điều hướng -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Du lịch Hóc Môn</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" href="#">Trang Chủ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#about">Giới Thiệu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#tourism">Địa Điểm Du Lịch</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#contact">Liên Hệ</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Hero Section -->
  <div class="hero">
    <h1>Khám Phá Hóc Môn</h1>
  </div>

  <!-- Giới thiệu về Hóc Môn -->
  <div class="container mt-5" id="about">
    <h2>Giới thiệu về Hóc Môn</h2>
    <p>Hóc Môn là một huyện nằm ở phía Tây Bắc của Thành phố Hồ Chí Minh. Đây là vùng đất giàu truyền thống lịch sử và văn hóa, gắn liền với những giai đoạn phát triển quan trọng của đất nước.</p>
    <p>Ngoài ra, Hóc Môn còn nổi tiếng với các nghề truyền thống như trồng trầu. Đặc biệt, "18 thôn vườn trầu" đã trở thành biểu tượng của địa phương này với bề dày lịch sử và văn hóa lâu đời.</p>
  </div>

  <!-- Địa Điểm Du Lịch Nổi Bật -->
  <div class="container mt-5" id="tourism">
    <h2>Địa điểm du lịch nổi bật</h2>
    <div class="row">
      <div class="col-md-6">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Cho_Hoc_Mon.JPG/1280px-Cho_Hoc_Mon.JPG" alt="18 thôn vườn trầu" class="img-fluid">
      </div>
      <div class="col-md-6">
        <h3>18 thôn vườn trầu</h3>
        <p>"18 thôn vườn trầu" là địa danh nổi tiếng tại Hóc Môn, gắn liền với lịch sử đấu tranh cách mạng của dân tộc. Đây là khu vực với nhiều vườn trầu xanh bạt ngàn, mang đậm nét truyền thống nông thôn Việt Nam.</p>
        <p>Đến tham quan 18 thôn vườn trầu, du khách sẽ được chiêm ngưỡng không chỉ cảnh quan thiên nhiên tuyệt đẹp mà còn được tìm hiểu về văn hóa trồng trầu của người dân nơi đây.</p>
      </div>
    </div>
  </div>

  <!-- Phần Liên Hệ -->
  <div class="container mt-5 mb-5" id="contact">
    <h2>Liên Hệ</h2>
    <p>Nếu bạn có thắc mắc hoặc muốn tìm hiểu thêm về Hóc Môn, hãy liên hệ với chúng tôi qua:</p>
    <ul>
      <li>Email: dulichhocmon@example.com</li>
      <li>Điện thoại: 0123-456-789</li>
    </ul>
  </div>

  <!-- Footer -->
  <footer class="bg-dark text-white text-center py-3">
    <p>&copy; 2024 Du lịch Hóc Môn. All rights reserved.</p>
  </footer>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
